### ISSUE TITLE
stdlib: "atoi()" not working with some numbers

### ISSUE THREAD

**Issue by matheuspb** [nanvix/nanvix#104]
`atoi` is returning wrong values with negative integers and numbers ending in `0`, e.g.:

- `atoi("-1") -> 4294967295`
- `atoi("-10") -> 4294967295`
- `atoi("10") -> 1`
- `atoi("100") -> 1`

Apparently the problem is in the `strtol` function.

**Comment by zambonin** [comment]
This also causes commands such as `nice` to behave incorrectly, e.g. `ps` shows that `nice -n -10 foobar` decreases the `nice` counter by one instead of ten.

**Comment by ppenna** [comment]
Hi,

I suppose that you are both referring to the atoi() implementation in the 'master' branch.

Indeed, this branch stands out for the educational version of Nanvix, which has partial support for the standard C library.

Please refer to the 'dev' branch to a state-of-the-art implementation of Nanvix.

Cheers,
Pedro H. Penna

**Comment by ppenna** [comment]
Issue fixed in commit 8fdc5090ab11c3ee084ec82317655930cf45c028.
