### ISSUE TITLE
Allow usage on containers (e.g Docker and LXC)

### ISSUE THREAD

**Issue by fjorgemota** [nanvix/nanvix#106]
Actually, to compile Nanvix, there is a need to use some commands that can be done only with super-user permissions, like mounting an image, for example.

Some of these commands (like mounting an image..) cannot be done on a container without privileged access, as the default provided by Docker and LXC. There, the command fails because a user cannot mount an image inside a container since the kernel is shared (and a `mount` operation may cause security problems at that level).

We should research and develop a way to allow the creation of the image even on containers. First, it was considered the usage of FUSE to do that, but even FUSE cannot be done inside a container. Actually, the best option found (so far) is [libguestfs](http://libguestfs.org/), which opens an image exactly  as Linux does and allow the user to do traditional filesystem actions here, like move a file, create folders, etc., but without super user privileges (and running even inside containers).

This issue is meant to track the fix of the development related to this problem, which I will do in a near future.

**Comment by Theldus** [comment]
Just giving my two cents, in the dev branch, if compiled with the flag '--build-iso', there is no need to mount images and no privileged access is required to the system, but since I do not understand properly how containers work I don't know if this info could be useful to you.

**Comment by fjorgemota** [comment]
Well, I will search about that flag and do the test, so.

Howver, this issue is more focused on Nanvix's educational version, because some universities (like UFSC) use LXC to provide virtual machine to it's users and it helps in development too (because containers are really lightweight compared to virtual machines..).

Thanks for your comment. =)

**Comment by ppenna** [comment]
Feature introduced in commit 1967eb411cf0235e4728cd61bd6cc524a0db6ede.
