### ISSUE TITLE
Kernel Error from Userland Inside a fork()

### ISSUE THREAD

**Issue by Mesh33** [nanvix/nanvix#139]
**Brief**
The follow code causes a kernel panic.
```
static int sem_test(void)
{
	if (fork() == 0)
	{
		/* child */
		int *i;
		i = NULL;
		printf("%d \n",*i);
	}
	else
	{

	}

	return (0);
}
```
**Further Information**

* Accessing the pointer initialized to "NULL" will result in a kernel panic.
* If the code is inside the father, there will only be a memory violation.

**Comment by ppenna** [comment]
Unit test introduced for tracking this error in commit https://github.com/nanvix/nanvix/commits/dev.

**Comment by Theldus** [comment]
I think I understood the problem, it happens that the child process when it tries to access the invalid portion of memory, `do_page_fault()` is triggered with error code 5. Giving a quick look at error codes [here](http://wiki.osdev.org/Exceptions#Page_Fault), and looking at this snippet of code (src/kernel/arch/x86/exception.c):
```c
/* Validty page fault. */
if (!(err & 1))
{
	if (!vfault(addr))
		return;
}
	
/* Protection page fault. */
if (err & 2)
{
	if (!pfault(addr))
		return;
}
	
if (KERNEL_RUNNING(curr_proc))
{
	dumpregs(&s);
	kpanic("kernel page fault %d at %x", err, addr);
}
```
the code 101 (flags UWP - User/Page read/Protection violation) is not treated in either the first `if` nor the second one, and once `intlvl` is > 1, the kernel panic is fired.

I believe that error code 5 could be dealt in the same way as 7, but maybe you can check separately, for instance:
```c
if ( (addr == 0) && (err & 4) )
	goto sigsegv;
...
sigsegv:
	sndsig(curr_proc, SIGSEGV);
	die(((SIGSEGV & 0xff) << 16) | (1 << 9));
```
