### ISSUE TITLE
Initrd Overflow

### ISSUE THREAD

**Issue by ppenna** [nanvix/nanvix#215]
**Description**

The ``initrd`` is suffering from overflow. The overall size of all binaries is exceeding the maximum size for the ``initrd``.

Since increasing the size of the  ``initrd``is not possible, we should work on the following solution: reduce the size of binaries and eventually compressing them.

**Update**

Stripping binary files solves the problem for the x86 architecture.

**Comment by gbesnard** [comment]
Fix #219
