### ISSUE TITLE
GDB building error

### ISSUE THREAD

**Issue by gbesnard** [nanvix/nanvix#220]
**Descrption**

I had these errors with gcc 8.1.0 but was able to reproduce it with gcc-6 and gcc-5 on both or1k and i386.
[gdb-errors-compilation.log](https://github.com/nanvix/nanvix/files/2031770/gdb-errors-compilation.log)

For i386, gdb-8.1 seems to correct the building errors
[http://ftp.gnu.org/gnu/gdb/gdb-8.1.tar.gz](url)

And its counterpart for or1k
[https://github.com/bminor/binutils-gdb/archive/gdb-8.1-release.tar.gz](url)

**Comment by Theldus** [comment]
I didn't understand, the current toolchain in the nanvix/toolchain works fine here, both binutils/gcc/gdb for i386 and or1k. By gcc 5/6 you mean in the host machine? moreover, the gdb used for or1k is the 7.11 not 8.1.

**Comment by gbesnard** [comment]
Sorry I wasn't clear enough. 

I'm indeed saying that I tried with both gcc 6, 7 and 8 (on my host machine) to build the gdb contained in the toolchain (running the toolchain script). And it fails for me in all cases (as shown in the gdb log). 

So it seems to be a problem coming from my environment if you are not experiencing it. Maybe I can try to run it in a Ubuntu docker to check if the compile correctly end up with a gdb binary.

What I then wanted to say is that if I change the gdb in the toolchain with a more recent version, 8.1, it builds fine for me.

**Comment by Theldus** [comment]
> What I then wanted to say is that if I change the gdb in the toolchain with a more recent version, 8.1, it builds fine for me.

Oohh, I got it.  You have issues building both GDB for or1k and i386? For i386 you can use your host GDB more-or-less safely because it's the same arch, while for or1k you'll have to use the or1k version, but this error is pretty strange.

**Comment by gbesnard** [comment]
Thanks for having a look. I found the bug issue : 
[https://sourceware.org/bugzilla/show_bug.cgi?id=21104](url)

In short, running Arch Linux on my host computer (silly me), I have both **guile 2.2** and **2.0** installed. It seems **gdb 8.0** doesn't build with **guile 2.2** but will chose it anyway for the compilation if available. I have checked on a Ubuntu and it seems that **guile 2.0** is used in the official repo, explaining why you would not have errors (I assume you run Ubuntu based distro by looking at the **setup-toolchain.sh** script).

This issue seems to have been fixed upstream, explaining that it worked for me with **gdb 8.1**.

One fix working for me is to add in the **setup-toolchain-arch.sh** `--with-guile=guile-2.0` in the _configure_ for **gdb**.

So I guess to close this issue we could :

- Patch the script with the argument `--with-guile=guile-2.0` (with the risk of forgetting it when updating to a newer version of **gdb**)
- Update our toolchain to **gdb 8.1**
- Do nothing and consider this case to be an isolated one.

**Comment by Theldus** [comment]
Hmmm, very interesting...
I don't blame you... I use Slackware here =), but we use Debian-based distros as reference, since would be hard to address every popular distro inside the building scripts.

Reading the link you sent, it seems that Guile allows to write scripts in Scheme inside the GDB, just as it's possible with Python... thinking that the latest GDB for or1k is 7.11 maybe then our best option is just not to use Guile, with the `--with-guile=no` option, could you try this and tell us if it works?

**Comment by gbesnard** [comment]
Yes it runs fine for both architectures. (I was also able to attach to nanvix with gdb).
Should I make a pull request to add this change then ? 
While I'm at it, I could also add the **--dbg** case to our **run-qemu.sh** script for or1k.

**Comment by Theldus** [comment]
Nice, yes, since the changes are straightforward, I think the PR worth it.

> Edit: Actually, running ddd while having a nanvix with no-display option messes the io for me, I had better luck attaching to it "manually" from another terminal.

DDD is a bit buggy but is great for viewing structures. GDB with tui is also interesting, I use a lot in or1k, things like:
```
layout src
layout asm
layout regs.....
```

**Comment by ppenna** [comment]
Bug fixed in commit fd31089bfab49c766b30f68df9fbcc86d95b8774.
